[package]
name = "chemarium"
version = "0.0.0"
authors = ["SchokiCoder <afschoknecht@gmail.com>"]
edition = "2018"
license = "GPLv3"
publish = false

[dependencies]

[dependencies.sdl2]
version = "0.35.*"
default-features = false
features = ["ttf"]
